name: "Enhancement Request"
description: Is something critical missing? Suggest an enhancement or feature.
title: ""
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Before filing an enhancement or feature, please [search the existing issues](https://github.com/vmware-samples/validated-solutions-for-cloud-foundation/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) for related requests, and use the [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) feature to add up-votes to existing requests.
        
        When filing an enhancement issue, please include the following information.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a [Code of Conduct](https://github.com/vmware-samples/validated-solutions-for-cloud-foundation/main/CODE_OF_CONDUCT.md) that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's Code of Conduct.
          required: true
        - label: Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
          required: false
        - label: Do not leave "+1" or other comments that do not add relevant information or questions.
          required: false
        - label: If you are interested in working on this issue or have submitted a pull request, please leave a comment.
          required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A written overview of the enhancement or feature.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case(s)
      description: Please provide a use case or scenario.
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Potential Configuration
      description: |
        Provide a potential configuration.
        Learn more about [Code Formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).
      placeholder: |
        Please format any code in code blocks using the markdown editor.
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Please provide any related GitHub issues or pull requests (open or closed) or documentation.
        Learn about [Referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests).
      placeholder: |
        #GH-0000
    validations:
      required: false